services:
  admin-app:
    build: .
    container_name: admin-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./app:/app/app:ro
      - ./main.py:/app/main.py:ro
